
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Aug 13 2025 22:13:33 IST (Aug 13 2025 16:43:33 UTC)

// Verification Directory fv/fifo1 

module fifo1(rdata, full, empty, wdata, w_en, wclk, wrst_n, r_en, rclk,
     rrst_n);
  input [7:0] wdata;
  input w_en, wclk, wrst_n, r_en, rclk, rrst_n;
  output [7:0] rdata;
  output full, empty;
  wire [7:0] wdata;
  wire w_en, wclk, wrst_n, r_en, rclk, rrst_n;
  wire [7:0] rdata;
  wire full, empty;
  wire [4:0] w2r_wptr;
  wire [4:0] r2w_rptr;
  wire [4:0] w1_w2r_temp;
  wire [4:0] r1_r2w_temp;
  wire [4:0] wptr;
  wire [4:0] rptr;
  wire [7:0] \f1_mem[4] ;
  wire [7:0] \f1_mem[5] ;
  wire [7:0] \f1_mem[12] ;
  wire [7:0] \f1_mem[13] ;
  wire [7:0] \f1_mem[10] ;
  wire [7:0] \f1_mem[11] ;
  wire [7:0] \f1_mem[0] ;
  wire [7:0] \f1_mem[1] ;
  wire [7:0] \f1_mem[2] ;
  wire [7:0] \f1_mem[3] ;
  wire [7:0] \f1_mem[7] ;
  wire [7:0] \f1_mem[15] ;
  wire [7:0] \f1_mem[14] ;
  wire [7:0] \f1_mem[8] ;
  wire [7:0] \f1_mem[6] ;
  wire [3:0] waddr;
  wire [7:0] \f1_mem[9] ;
  wire [3:0] raddr;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_108, n_109, n_110, n_111, n_112, n_113;
  wire n_114, n_115, n_117, n_118, n_119, n_120, n_121, n_122;
  wire n_123, n_124, n_125, n_126, n_127, n_128, n_129, n_130;
  wire n_131, n_132, n_133, n_134, n_135, n_136, n_137, n_138;
  wire n_139, n_140, n_141, n_142, n_143, n_144, n_145, n_146;
  wire n_147, n_148, n_149, n_150, n_151, n_152, n_153, n_154;
  wire n_155, n_156, n_157, n_158, n_159, n_160, n_161, n_162;
  wire n_163, n_164, n_165, n_174, n_175, n_176, n_177, n_179;
  wire n_180, n_181, n_182, n_183, n_184, n_185, n_186, n_187;
  wire n_188, n_189, n_190, n_191, n_192, n_193, n_194, n_195;
  wire n_202, n_203;
  DFCNQD1 f2_wfull_reg(.CDN (wrst_n), .CP (wclk), .D (n_195), .Q
       (full));
  DFSNQD1 e1_rempty_reg(.SDN (rrst_n), .CP (rclk), .D (n_194), .Q
       (empty));
  NR4D0 g5930__2398(.A1 (n_192), .A2 (n_180), .A3 (n_184), .A4 (n_177),
       .ZN (n_195));
  NR4D0 g5931__5107(.A1 (n_193), .A2 (n_182), .A3 (n_141), .A4 (n_175),
       .ZN (n_194));
  OAI211D1 g5934__6260(.A1 (w2r_wptr[3]), .A2 (n_187), .B (n_188), .C
       (n_190), .ZN (n_193));
  OAI21D1 g5932__4319(.A1 (n_202), .A2 (r2w_rptr[4]), .B (n_191), .ZN
       (n_192));
  AOI221D0 g5933__8428(.A1 (n_179), .A2 (r2w_rptr[2]), .B1 (n_185), .B2
       (r2w_rptr[3]), .C (n_186), .ZN (n_191));
  MAOI22D1 g5936__5526(.A1 (n_189), .A2 (w2r_wptr[2]), .B1 (n_189), .B2
       (w2r_wptr[2]), .ZN (n_190));
  ND2D1 g5938__6783(.A1 (n_187), .A2 (w2r_wptr[3]), .ZN (n_188));
  DFKCNQD1 \w1_w2r_wptr_reg[3] (.CP (rclk), .CN (w1_w2r_temp[3]), .D
       (rrst_n), .Q (w2r_wptr[3]));
  NR2D1 g5935__3680(.A1 (n_185), .A2 (r2w_rptr[3]), .ZN (n_186));
  MAOI22D1 g5941__1617(.A1 (n_183), .A2 (r2w_rptr[1]), .B1 (n_183), .B2
       (r2w_rptr[1]), .ZN (n_184));
  MOAI22D1 g5946__2802(.A1 (n_181), .A2 (w2r_wptr[1]), .B1 (n_181), .B2
       (w2r_wptr[1]), .ZN (n_182));
  MOAI22D1 g5939__1705(.A1 (n_179), .A2 (r2w_rptr[2]), .B1 (n_202), .B2
       (r2w_rptr[4]), .ZN (n_180));
  DFKCNQD1 \w1_w2r_wptr_reg[2] (.CP (rclk), .CN (w1_w2r_temp[2]), .D
       (rrst_n), .Q (w2r_wptr[2]));
  DFKCNQD1 \r1_r2w_rptr_reg[3] (.CP (wclk), .CN (r1_r2w_temp[3]), .D
       (wrst_n), .Q (r2w_rptr[3]));
  MAOI22D1 g5945__5122(.A1 (n_176), .A2 (r2w_rptr[0]), .B1 (n_176), .B2
       (r2w_rptr[0]), .ZN (n_177));
  DFKCNQD1 \w1_w2r_temp_reg[3] (.CP (rclk), .CN (wptr[3]), .D (rrst_n),
       .Q (w1_w2r_temp[3]));
  MOAI22D1 g5950__8246(.A1 (n_174), .A2 (w2r_wptr[0]), .B1 (n_174), .B2
       (w2r_wptr[0]), .ZN (n_175));
  DFKCNQD1 \w1_w2r_temp_reg[2] (.CP (rclk), .CN (wptr[2]), .D (rrst_n),
       .Q (w1_w2r_temp[2]));
  DFKCNQD1 \r1_r2w_rptr_reg[2] (.CP (wclk), .CN (r1_r2w_temp[2]), .D
       (wrst_n), .Q (r2w_rptr[2]));
  DFKCNQD1 \r1_r2w_rptr_reg[1] (.CP (wclk), .CN (r1_r2w_temp[1]), .D
       (wrst_n), .Q (r2w_rptr[1]));
  DFKCNQD1 \w1_w2r_wptr_reg[1] (.CP (rclk), .CN (w1_w2r_temp[1]), .D
       (rrst_n), .Q (w2r_wptr[1]));
  ND4D1 g5970__7098(.A1 (n_157), .A2 (n_81), .A3 (n_37), .A4 (n_29),
       .ZN (rdata[6]));
  ND4D1 g5975__6131(.A1 (n_153), .A2 (n_87), .A3 (n_92), .A4 (n_21),
       .ZN (rdata[7]));
  DFKCNQD1 \r1_r2w_temp_reg[3] (.CP (wclk), .CN (rptr[3]), .D (wrst_n),
       .Q (r1_r2w_temp[3]));
  ND4D1 g5974__1881(.A1 (n_158), .A2 (n_78), .A3 (n_79), .A4 (n_36),
       .ZN (rdata[5]));
  ND4D1 g5968__5115(.A1 (n_163), .A2 (n_50), .A3 (n_77), .A4 (n_35),
       .ZN (rdata[2]));
  ND4D1 g5973__7482(.A1 (n_154), .A2 (n_52), .A3 (n_48), .A4 (n_23),
       .ZN (rdata[3]));
  ND4D1 g5971__4733(.A1 (n_165), .A2 (n_94), .A3 (n_70), .A4 (n_22),
       .ZN (rdata[4]));
  ND4D1 g5969__6161(.A1 (n_164), .A2 (n_68), .A3 (n_69), .A4 (n_25),
       .ZN (rdata[1]));
  ND4D1 g5967__9315(.A1 (n_161), .A2 (n_67), .A3 (n_91), .A4 (n_20),
       .ZN (rdata[0]));
  DFKCNQD1 \r1_r2w_rptr_reg[0] (.CP (wclk), .CN (r1_r2w_temp[0]), .D
       (wrst_n), .Q (r2w_rptr[0]));
  DFCNQD1 \f2_wptr_reg[3] (.CDN (wrst_n), .CP (wclk), .D (n_185), .Q
       (wptr[3]));
  DFKCNQD1 \w1_w2r_wptr_reg[0] (.CP (rclk), .CN (w1_w2r_temp[0]), .D
       (rrst_n), .Q (w2r_wptr[0]));
  DFKCNQD1 \w1_w2r_temp_reg[1] (.CP (rclk), .CN (wptr[1]), .D (rrst_n),
       .Q (w1_w2r_temp[1]));
  DFKCNQD1 \r1_r2w_temp_reg[2] (.CP (wclk), .CN (rptr[2]), .D (wrst_n),
       .Q (r1_r2w_temp[2]));
  DFKCNQD1 \r1_r2w_temp_reg[1] (.CP (wclk), .CN (rptr[1]), .D (wrst_n),
       .Q (r1_r2w_temp[1]));
  DFCNQD1 \f2_wptr_reg[2] (.CDN (wrst_n), .CP (wclk), .D (n_152), .Q
       (wptr[2]));
  DFCNQD1 \e1_rptr_reg[3] (.CDN (rrst_n), .CP (rclk), .D (n_151), .Q
       (rptr[3]));
  AOI221D0 g6056__9945(.A1 (n_160), .A2 (\f1_mem[4] [4]), .B1 (n_159),
       .B2 (\f1_mem[5] [4]), .C (n_143), .ZN (n_165));
  AOI221D0 g6058__2883(.A1 (n_156), .A2 (\f1_mem[12] [1]), .B1 (n_155),
       .B2 (\f1_mem[13] [1]), .C (n_148), .ZN (n_164));
  AOI221D0 g6057__2346(.A1 (n_108), .A2 (\f1_mem[10] [2]), .B1 (n_107),
       .B2 (\f1_mem[11] [2]), .C (n_145), .ZN (n_163));
  MOAI22D1 g5983__1666(.A1 (n_202), .A2 (n_162), .B1 (n_202), .B2
       (n_162), .ZN (n_185));
  AOI221D0 g6061__7410(.A1 (n_160), .A2 (\f1_mem[4] [0]), .B1 (n_159),
       .B2 (\f1_mem[5] [0]), .C (n_142), .ZN (n_161));
  AOI221D0 g6060__6417(.A1 (n_102), .A2 (\f1_mem[0] [5]), .B1 (n_203),
       .B2 (\f1_mem[1] [5]), .C (n_146), .ZN (n_158));
  AOI221D0 g6059__5477(.A1 (n_156), .A2 (\f1_mem[12] [6]), .B1 (n_155),
       .B2 (\f1_mem[13] [6]), .C (n_144), .ZN (n_157));
  AOI221D0 g6062__2398(.A1 (n_156), .A2 (\f1_mem[12] [3]), .B1 (n_155),
       .B2 (\f1_mem[13] [3]), .C (n_149), .ZN (n_154));
  AOI221D0 g6063__5107(.A1 (n_113), .A2 (\f1_mem[2] [7]), .B1 (n_112),
       .B2 (\f1_mem[3] [7]), .C (n_147), .ZN (n_153));
  DFKCNQD1 \r1_r2w_temp_reg[0] (.CP (wclk), .CN (rptr[0]), .D (wrst_n),
       .Q (r1_r2w_temp[0]));
  CKND1 g5981(.I (n_179), .ZN (n_152));
  DFKCNQD1 \w1_w2r_temp_reg[0] (.CP (rclk), .CN (wptr[0]), .D (rrst_n),
       .Q (w1_w2r_temp[0]));
  DFCNQD1 \f2_wbin_reg[4] (.CDN (wrst_n), .CP (wclk), .D (n_202), .Q
       (wptr[4]));
  CKND1 g5966(.I (n_187), .ZN (n_151));
  DFCNQD1 \e1_rptr_reg[2] (.CDN (rrst_n), .CP (rclk), .D (n_135), .Q
       (rptr[2]));
  MAOI22D1 g5984__6260(.A1 (n_162), .A2 (n_150), .B1 (n_162), .B2
       (n_150), .ZN (n_179));
  DFCNQD1 \e1_rptr_reg[1] (.CDN (rrst_n), .CP (rclk), .D (n_136), .Q
       (rptr[1]));
  DFCNQD1 \f2_wptr_reg[1] (.CDN (wrst_n), .CP (wclk), .D (n_183), .Q
       (wptr[1]));
  ND4D1 g6122__4319(.A1 (n_106), .A2 (n_49), .A3 (n_89), .A4 (n_31),
       .ZN (n_149));
  ND4D1 g6123__8428(.A1 (n_103), .A2 (n_86), .A3 (n_59), .A4 (n_38),
       .ZN (n_148));
  ND4D1 g6113__5526(.A1 (n_99), .A2 (n_54), .A3 (n_66), .A4 (n_33), .ZN
       (n_147));
  ND4D1 g6114__6783(.A1 (n_105), .A2 (n_51), .A3 (n_71), .A4 (n_30),
       .ZN (n_146));
  ND4D1 g6115__3680(.A1 (n_100), .A2 (n_72), .A3 (n_93), .A4 (n_24),
       .ZN (n_145));
  ND4D1 g6119__1617(.A1 (n_114), .A2 (n_63), .A3 (n_90), .A4 (n_28),
       .ZN (n_144));
  ND4D1 g6120__2802(.A1 (n_104), .A2 (n_57), .A3 (n_83), .A4 (n_27),
       .ZN (n_143));
  ND4D1 g6121__1705(.A1 (n_109), .A2 (n_58), .A3 (n_82), .A4 (n_34),
       .ZN (n_142));
  MAOI22D1 g5972__5122(.A1 (n_140), .A2 (w2r_wptr[4]), .B1 (n_140), .B2
       (w2r_wptr[4]), .ZN (n_141));
  SDFQD0 \f1_mem_reg[7][4] (.CP (wclk), .D (\f1_mem[7] [4]), .SI
       (wdata[4]), .SE (n_139), .Q (\f1_mem[7] [4]));
  SDFQD0 \f1_mem_reg[7][0] (.CP (wclk), .D (\f1_mem[7] [0]), .SI
       (wdata[0]), .SE (n_139), .Q (\f1_mem[7] [0]));
  MAOI22D1 g5977__8246(.A1 (n_140), .A2 (n_138), .B1 (n_140), .B2
       (n_138), .ZN (n_187));
  SDFQD0 \f1_mem_reg[15][1] (.CP (wclk), .D (\f1_mem[15] [1]), .SI
       (wdata[1]), .SE (n_137), .Q (\f1_mem[15] [1]));
  SDFQD0 \f1_mem_reg[7][2] (.CP (wclk), .D (\f1_mem[7] [2]), .SI
       (wdata[2]), .SE (n_139), .Q (\f1_mem[7] [2]));
  SDFQD0 \f1_mem_reg[7][3] (.CP (wclk), .D (\f1_mem[7] [3]), .SI
       (wdata[3]), .SE (n_139), .Q (\f1_mem[7] [3]));
  SDFQD0 \f1_mem_reg[7][5] (.CP (wclk), .D (\f1_mem[7] [5]), .SI
       (wdata[5]), .SE (n_139), .Q (\f1_mem[7] [5]));
  SDFQD0 \f1_mem_reg[7][6] (.CP (wclk), .D (\f1_mem[7] [6]), .SI
       (wdata[6]), .SE (n_139), .Q (\f1_mem[7] [6]));
  SDFQD0 \f1_mem_reg[7][7] (.CP (wclk), .D (\f1_mem[7] [7]), .SI
       (wdata[7]), .SE (n_139), .Q (\f1_mem[7] [7]));
  SDFQD0 \f1_mem_reg[15][7] (.CP (wclk), .D (\f1_mem[15] [7]), .SI
       (wdata[7]), .SE (n_137), .Q (\f1_mem[15] [7]));
  SDFQD0 \f1_mem_reg[15][5] (.CP (wclk), .D (\f1_mem[15] [5]), .SI
       (wdata[5]), .SE (n_137), .Q (\f1_mem[15] [5]));
  SDFQD0 \f1_mem_reg[15][6] (.CP (wclk), .D (\f1_mem[15] [6]), .SI
       (wdata[6]), .SE (n_137), .Q (\f1_mem[15] [6]));
  SDFQD0 \f1_mem_reg[15][3] (.CP (wclk), .D (\f1_mem[15] [3]), .SI
       (wdata[3]), .SE (n_137), .Q (\f1_mem[15] [3]));
  SDFQD0 \f1_mem_reg[15][2] (.CP (wclk), .D (\f1_mem[15] [2]), .SI
       (wdata[2]), .SE (n_137), .Q (\f1_mem[15] [2]));
  SDFQD0 \f1_mem_reg[15][4] (.CP (wclk), .D (\f1_mem[15] [4]), .SI
       (wdata[4]), .SE (n_137), .Q (\f1_mem[15] [4]));
  SDFQD0 \f1_mem_reg[15][0] (.CP (wclk), .D (\f1_mem[15] [0]), .SI
       (wdata[0]), .SE (n_137), .Q (\f1_mem[15] [0]));
  SDFQD0 \f1_mem_reg[7][1] (.CP (wclk), .D (\f1_mem[7] [1]), .SI
       (wdata[1]), .SE (n_139), .Q (\f1_mem[7] [1]));
  CKND1 g6055(.I (n_181), .ZN (n_136));
  CKND1 g5992(.I (n_189), .ZN (n_135));
  DFCNQD1 \f2_wptr_reg[0] (.CDN (wrst_n), .CP (wclk), .D (n_176), .Q
       (wptr[0]));
  SDFQD0 \f1_mem_reg[13][3] (.CP (wclk), .D (\f1_mem[13] [3]), .SI
       (wdata[3]), .SE (n_134), .Q (\f1_mem[13] [3]));
  SDFQD0 \f1_mem_reg[13][2] (.CP (wclk), .D (\f1_mem[13] [2]), .SI
       (wdata[2]), .SE (n_134), .Q (\f1_mem[13] [2]));
  SDFQD0 \f1_mem_reg[11][5] (.CP (wclk), .D (wdata[5]), .SI
       (\f1_mem[11] [5]), .SE (n_131), .Q (\f1_mem[11] [5]));
  SDFQD0 \f1_mem_reg[13][0] (.CP (wclk), .D (\f1_mem[13] [0]), .SI
       (wdata[0]), .SE (n_134), .Q (\f1_mem[13] [0]));
  SDFQD0 \f1_mem_reg[13][1] (.CP (wclk), .D (\f1_mem[13] [1]), .SI
       (wdata[1]), .SE (n_134), .Q (\f1_mem[13] [1]));
  SDFQD0 \f1_mem_reg[13][7] (.CP (wclk), .D (\f1_mem[13] [7]), .SI
       (wdata[7]), .SE (n_134), .Q (\f1_mem[13] [7]));
  MOAI22D1 g6124__6131(.A1 (n_150), .A2 (n_133), .B1 (n_150), .B2
       (n_133), .ZN (n_183));
  DFCNQD1 \e1_rbin_reg[4] (.CDN (rrst_n), .CP (rclk), .D (n_140), .Q
       (rptr[4]));
  CKND1 g6000(.I (n_162), .ZN (n_132));
  DFCNQD1 \e1_rptr_reg[0] (.CDN (rrst_n), .CP (rclk), .D (n_115), .Q
       (rptr[0]));
  SDFQD0 \f1_mem_reg[13][6] (.CP (wclk), .D (\f1_mem[13] [6]), .SI
       (wdata[6]), .SE (n_134), .Q (\f1_mem[13] [6]));
  SDFQD0 \f1_mem_reg[11][7] (.CP (wclk), .D (wdata[7]), .SI
       (\f1_mem[11] [7]), .SE (n_131), .Q (\f1_mem[11] [7]));
  SDFQD0 \f1_mem_reg[13][5] (.CP (wclk), .D (\f1_mem[13] [5]), .SI
       (wdata[5]), .SE (n_134), .Q (\f1_mem[13] [5]));
  SDFQD0 \f1_mem_reg[11][0] (.CP (wclk), .D (wdata[0]), .SI
       (\f1_mem[11] [0]), .SE (n_131), .Q (\f1_mem[11] [0]));
  SDFQD0 \f1_mem_reg[13][4] (.CP (wclk), .D (\f1_mem[13] [4]), .SI
       (wdata[4]), .SE (n_134), .Q (\f1_mem[13] [4]));
  SDFQD0 \f1_mem_reg[11][2] (.CP (wclk), .D (wdata[2]), .SI
       (\f1_mem[11] [2]), .SE (n_131), .Q (\f1_mem[11] [2]));
  SDFQD0 \f1_mem_reg[11][3] (.CP (wclk), .D (wdata[3]), .SI
       (\f1_mem[11] [3]), .SE (n_131), .Q (\f1_mem[11] [3]));
  SDFQD0 \f1_mem_reg[11][4] (.CP (wclk), .D (wdata[4]), .SI
       (\f1_mem[11] [4]), .SE (n_131), .Q (\f1_mem[11] [4]));
  SDFQD0 \f1_mem_reg[11][6] (.CP (wclk), .D (wdata[6]), .SI
       (\f1_mem[11] [6]), .SE (n_131), .Q (\f1_mem[11] [6]));
  SDFQD0 \f1_mem_reg[11][1] (.CP (wclk), .D (wdata[1]), .SI
       (\f1_mem[11] [1]), .SE (n_131), .Q (\f1_mem[11] [1]));
  SDFQD0 \f1_mem_reg[0][5] (.CP (wclk), .D (wdata[5]), .SI
       (\f1_mem[0] [5]), .SE (n_126), .Q (\f1_mem[0] [5]));
  SDFQD0 \f1_mem_reg[3][5] (.CP (wclk), .D (wdata[5]), .SI
       (\f1_mem[3] [5]), .SE (n_130), .Q (\f1_mem[3] [5]));
  SDFQD0 \f1_mem_reg[5][1] (.CP (wclk), .D (wdata[1]), .SI
       (\f1_mem[5] [1]), .SE (n_129), .Q (\f1_mem[5] [1]));
  SDFQD0 \f1_mem_reg[3][1] (.CP (wclk), .D (wdata[1]), .SI
       (\f1_mem[3] [1]), .SE (n_130), .Q (\f1_mem[3] [1]));
  SDFQD0 \f1_mem_reg[14][3] (.CP (wclk), .D (\f1_mem[14] [3]), .SI
       (wdata[3]), .SE (n_128), .Q (\f1_mem[14] [3]));
  SDFQD0 \f1_mem_reg[5][0] (.CP (wclk), .D (wdata[0]), .SI
       (\f1_mem[5] [0]), .SE (n_129), .Q (\f1_mem[5] [0]));
  SDFQD0 \f1_mem_reg[8][5] (.CP (wclk), .D (\f1_mem[8] [5]), .SI
       (wdata[5]), .SE (n_125), .Q (\f1_mem[8] [5]));
  SDFQD0 \f1_mem_reg[14][7] (.CP (wclk), .D (\f1_mem[14] [7]), .SI
       (wdata[7]), .SE (n_128), .Q (\f1_mem[14] [7]));
  SDFQD0 \f1_mem_reg[2][3] (.CP (wclk), .D (wdata[3]), .SI
       (\f1_mem[2] [3]), .SE (n_124), .Q (\f1_mem[2] [3]));
  SDFQD0 \f1_mem_reg[1][7] (.CP (wclk), .D (wdata[7]), .SI
       (\f1_mem[1] [7]), .SE (n_127), .Q (\f1_mem[1] [7]));
  SDFQD0 \f1_mem_reg[1][3] (.CP (wclk), .D (wdata[3]), .SI
       (\f1_mem[1] [3]), .SE (n_127), .Q (\f1_mem[1] [3]));
  SDFQD0 \f1_mem_reg[0][1] (.CP (wclk), .D (wdata[1]), .SI
       (\f1_mem[0] [1]), .SE (n_126), .Q (\f1_mem[0] [1]));
  SDFQD0 \f1_mem_reg[8][6] (.CP (wclk), .D (\f1_mem[8] [6]), .SI
       (wdata[6]), .SE (n_125), .Q (\f1_mem[8] [6]));
  SDFQD0 \f1_mem_reg[4][7] (.CP (wclk), .D (\f1_mem[4] [7]), .SI
       (wdata[7]), .SE (n_123), .Q (\f1_mem[4] [7]));
  SDFQD0 \f1_mem_reg[6][7] (.CP (wclk), .D (\f1_mem[6] [7]), .SI
       (wdata[7]), .SE (n_122), .Q (\f1_mem[6] [7]));
  SDFQD0 \f1_mem_reg[12][7] (.CP (wclk), .D (\f1_mem[12] [7]), .SI
       (wdata[7]), .SE (n_120), .Q (\f1_mem[12] [7]));
  SDFQD0 \f1_mem_reg[5][3] (.CP (wclk), .D (wdata[3]), .SI
       (\f1_mem[5] [3]), .SE (n_129), .Q (\f1_mem[5] [3]));
  SDFQD0 \f1_mem_reg[2][7] (.CP (wclk), .D (wdata[7]), .SI
       (\f1_mem[2] [7]), .SE (n_124), .Q (\f1_mem[2] [7]));
  SDFQD0 \f1_mem_reg[10][3] (.CP (wclk), .D (\f1_mem[10] [3]), .SI
       (wdata[3]), .SE (n_121), .Q (\f1_mem[10] [3]));
  SDFQD0 \f1_mem_reg[0][7] (.CP (wclk), .D (wdata[7]), .SI
       (\f1_mem[0] [7]), .SE (n_126), .Q (\f1_mem[0] [7]));
  SDFQD0 \f1_mem_reg[4][6] (.CP (wclk), .D (\f1_mem[4] [6]), .SI
       (wdata[6]), .SE (n_123), .Q (\f1_mem[4] [6]));
  SDFQD0 \f1_mem_reg[5][7] (.CP (wclk), .D (wdata[7]), .SI
       (\f1_mem[5] [7]), .SE (n_129), .Q (\f1_mem[5] [7]));
  SDFQD0 \f1_mem_reg[4][3] (.CP (wclk), .D (\f1_mem[4] [3]), .SI
       (wdata[3]), .SE (n_123), .Q (\f1_mem[4] [3]));
  SDFQD0 \f1_mem_reg[0][3] (.CP (wclk), .D (wdata[3]), .SI
       (\f1_mem[0] [3]), .SE (n_126), .Q (\f1_mem[0] [3]));
  SDFQD0 \f1_mem_reg[0][4] (.CP (wclk), .D (wdata[4]), .SI
       (\f1_mem[0] [4]), .SE (n_126), .Q (\f1_mem[0] [4]));
  SDFQD0 \f1_mem_reg[6][3] (.CP (wclk), .D (\f1_mem[6] [3]), .SI
       (wdata[3]), .SE (n_122), .Q (\f1_mem[6] [3]));
  SDFQD0 \f1_mem_reg[0][6] (.CP (wclk), .D (wdata[6]), .SI
       (\f1_mem[0] [6]), .SE (n_126), .Q (\f1_mem[0] [6]));
  SDFQD0 \f1_mem_reg[1][0] (.CP (wclk), .D (wdata[0]), .SI
       (\f1_mem[1] [0]), .SE (n_127), .Q (\f1_mem[1] [0]));
  SDFQD0 \f1_mem_reg[1][1] (.CP (wclk), .D (wdata[1]), .SI
       (\f1_mem[1] [1]), .SE (n_127), .Q (\f1_mem[1] [1]));
  SDFQD0 \f1_mem_reg[1][2] (.CP (wclk), .D (wdata[2]), .SI
       (\f1_mem[1] [2]), .SE (n_127), .Q (\f1_mem[1] [2]));
  SDFQD0 \f1_mem_reg[1][4] (.CP (wclk), .D (wdata[4]), .SI
       (\f1_mem[1] [4]), .SE (n_127), .Q (\f1_mem[1] [4]));
  SDFQD0 \f1_mem_reg[1][5] (.CP (wclk), .D (wdata[5]), .SI
       (\f1_mem[1] [5]), .SE (n_127), .Q (\f1_mem[1] [5]));
  SDFQD0 \f1_mem_reg[1][6] (.CP (wclk), .D (wdata[6]), .SI
       (\f1_mem[1] [6]), .SE (n_127), .Q (\f1_mem[1] [6]));
  SDFQD0 \f1_mem_reg[10][7] (.CP (wclk), .D (\f1_mem[10] [7]), .SI
       (wdata[7]), .SE (n_121), .Q (\f1_mem[10] [7]));
  SDFQD0 \f1_mem_reg[2][0] (.CP (wclk), .D (wdata[0]), .SI
       (\f1_mem[2] [0]), .SE (n_124), .Q (\f1_mem[2] [0]));
  SDFQD0 \f1_mem_reg[2][1] (.CP (wclk), .D (wdata[1]), .SI
       (\f1_mem[2] [1]), .SE (n_124), .Q (\f1_mem[2] [1]));
  SDFQD0 \f1_mem_reg[2][2] (.CP (wclk), .D (wdata[2]), .SI
       (\f1_mem[2] [2]), .SE (n_124), .Q (\f1_mem[2] [2]));
  SDFQD0 \f1_mem_reg[2][4] (.CP (wclk), .D (wdata[4]), .SI
       (\f1_mem[2] [4]), .SE (n_124), .Q (\f1_mem[2] [4]));
  SDFQD0 \f1_mem_reg[2][5] (.CP (wclk), .D (wdata[5]), .SI
       (\f1_mem[2] [5]), .SE (n_124), .Q (\f1_mem[2] [5]));
  SDFQD0 \f1_mem_reg[2][6] (.CP (wclk), .D (wdata[6]), .SI
       (\f1_mem[2] [6]), .SE (n_124), .Q (\f1_mem[2] [6]));
  SDFQD0 \f1_mem_reg[12][5] (.CP (wclk), .D (\f1_mem[12] [5]), .SI
       (wdata[5]), .SE (n_120), .Q (\f1_mem[12] [5]));
  SDFQD0 \f1_mem_reg[4][0] (.CP (wclk), .D (\f1_mem[4] [0]), .SI
       (wdata[0]), .SE (n_123), .Q (\f1_mem[4] [0]));
  SDFQD0 \f1_mem_reg[4][1] (.CP (wclk), .D (\f1_mem[4] [1]), .SI
       (wdata[1]), .SE (n_123), .Q (\f1_mem[4] [1]));
  SDFQD0 \f1_mem_reg[4][2] (.CP (wclk), .D (\f1_mem[4] [2]), .SI
       (wdata[2]), .SE (n_123), .Q (\f1_mem[4] [2]));
  SDFQD0 \f1_mem_reg[4][4] (.CP (wclk), .D (\f1_mem[4] [4]), .SI
       (wdata[4]), .SE (n_123), .Q (\f1_mem[4] [4]));
  SDFQD0 \f1_mem_reg[4][5] (.CP (wclk), .D (\f1_mem[4] [5]), .SI
       (wdata[5]), .SE (n_123), .Q (\f1_mem[4] [5]));
  MAOI22D1 g6109__1881(.A1 (n_119), .A2 (n_118), .B1 (n_119), .B2
       (n_118), .ZN (n_181));
  MAOI22D1 g5998__5115(.A1 (n_138), .A2 (n_119), .B1 (n_138), .B2
       (n_119), .ZN (n_189));
  AOI21D1 g6116__7482(.A1 (n_95), .A2 (waddr[3]), .B (n_139), .ZN
       (n_162));
  SDFQD0 \f1_mem_reg[9][2] (.CP (wclk), .D (wdata[2]), .SI
       (\f1_mem[9] [2]), .SE (n_117), .Q (\f1_mem[9] [2]));
  SDFQD0 \f1_mem_reg[5][4] (.CP (wclk), .D (wdata[4]), .SI
       (\f1_mem[5] [4]), .SE (n_129), .Q (\f1_mem[5] [4]));
  SDFQD0 \f1_mem_reg[5][5] (.CP (wclk), .D (wdata[5]), .SI
       (\f1_mem[5] [5]), .SE (n_129), .Q (\f1_mem[5] [5]));
  SDFQD0 \f1_mem_reg[5][6] (.CP (wclk), .D (wdata[6]), .SI
       (\f1_mem[5] [6]), .SE (n_129), .Q (\f1_mem[5] [6]));
  SDFQD0 \f1_mem_reg[6][0] (.CP (wclk), .D (\f1_mem[6] [0]), .SI
       (wdata[0]), .SE (n_122), .Q (\f1_mem[6] [0]));
  SDFQD0 \f1_mem_reg[6][1] (.CP (wclk), .D (\f1_mem[6] [1]), .SI
       (wdata[1]), .SE (n_122), .Q (\f1_mem[6] [1]));
  SDFQD0 \f1_mem_reg[6][2] (.CP (wclk), .D (\f1_mem[6] [2]), .SI
       (wdata[2]), .SE (n_122), .Q (\f1_mem[6] [2]));
  SDFQD0 \f1_mem_reg[6][4] (.CP (wclk), .D (\f1_mem[6] [4]), .SI
       (wdata[4]), .SE (n_122), .Q (\f1_mem[6] [4]));
  SDFQD0 \f1_mem_reg[6][5] (.CP (wclk), .D (\f1_mem[6] [5]), .SI
       (wdata[5]), .SE (n_122), .Q (\f1_mem[6] [5]));
  SDFQD0 \f1_mem_reg[6][6] (.CP (wclk), .D (\f1_mem[6] [6]), .SI
       (wdata[6]), .SE (n_122), .Q (\f1_mem[6] [6]));
  SDFQD0 \f1_mem_reg[8][0] (.CP (wclk), .D (\f1_mem[8] [0]), .SI
       (wdata[0]), .SE (n_125), .Q (\f1_mem[8] [0]));
  SDFQD0 \f1_mem_reg[8][1] (.CP (wclk), .D (\f1_mem[8] [1]), .SI
       (wdata[1]), .SE (n_125), .Q (\f1_mem[8] [1]));
  SDFQD0 \f1_mem_reg[8][2] (.CP (wclk), .D (\f1_mem[8] [2]), .SI
       (wdata[2]), .SE (n_125), .Q (\f1_mem[8] [2]));
  SDFQD0 \f1_mem_reg[8][4] (.CP (wclk), .D (\f1_mem[8] [4]), .SI
       (wdata[4]), .SE (n_125), .Q (\f1_mem[8] [4]));
  SDFQD0 \f1_mem_reg[5][2] (.CP (wclk), .D (wdata[2]), .SI
       (\f1_mem[5] [2]), .SE (n_129), .Q (\f1_mem[5] [2]));
  SDFQD0 \f1_mem_reg[9][6] (.CP (wclk), .D (wdata[6]), .SI
       (\f1_mem[9] [6]), .SE (n_117), .Q (\f1_mem[9] [6]));
  SDFQD0 \f1_mem_reg[10][0] (.CP (wclk), .D (\f1_mem[10] [0]), .SI
       (wdata[0]), .SE (n_121), .Q (\f1_mem[10] [0]));
  SDFQD0 \f1_mem_reg[10][1] (.CP (wclk), .D (\f1_mem[10] [1]), .SI
       (wdata[1]), .SE (n_121), .Q (\f1_mem[10] [1]));
  SDFQD0 \f1_mem_reg[10][2] (.CP (wclk), .D (\f1_mem[10] [2]), .SI
       (wdata[2]), .SE (n_121), .Q (\f1_mem[10] [2]));
  SDFQD0 \f1_mem_reg[10][4] (.CP (wclk), .D (\f1_mem[10] [4]), .SI
       (wdata[4]), .SE (n_121), .Q (\f1_mem[10] [4]));
  SDFQD0 \f1_mem_reg[10][5] (.CP (wclk), .D (\f1_mem[10] [5]), .SI
       (wdata[5]), .SE (n_121), .Q (\f1_mem[10] [5]));
  SDFQD0 \f1_mem_reg[10][6] (.CP (wclk), .D (\f1_mem[10] [6]), .SI
       (wdata[6]), .SE (n_121), .Q (\f1_mem[10] [6]));
  SDFQD0 \f1_mem_reg[9][7] (.CP (wclk), .D (wdata[7]), .SI
       (\f1_mem[9] [7]), .SE (n_117), .Q (\f1_mem[9] [7]));
  SDFQD0 \f1_mem_reg[12][0] (.CP (wclk), .D (\f1_mem[12] [0]), .SI
       (wdata[0]), .SE (n_120), .Q (\f1_mem[12] [0]));
  SDFQD0 \f1_mem_reg[12][1] (.CP (wclk), .D (\f1_mem[12] [1]), .SI
       (wdata[1]), .SE (n_120), .Q (\f1_mem[12] [1]));
  SDFQD0 \f1_mem_reg[12][2] (.CP (wclk), .D (\f1_mem[12] [2]), .SI
       (wdata[2]), .SE (n_120), .Q (\f1_mem[12] [2]));
  SDFQD0 \f1_mem_reg[12][4] (.CP (wclk), .D (\f1_mem[12] [4]), .SI
       (wdata[4]), .SE (n_120), .Q (\f1_mem[12] [4]));
  SDFQD0 \f1_mem_reg[12][6] (.CP (wclk), .D (\f1_mem[12] [6]), .SI
       (wdata[6]), .SE (n_120), .Q (\f1_mem[12] [6]));
  SDFQD0 \f1_mem_reg[14][0] (.CP (wclk), .D (\f1_mem[14] [0]), .SI
       (wdata[0]), .SE (n_128), .Q (\f1_mem[14] [0]));
  SDFQD0 \f1_mem_reg[14][1] (.CP (wclk), .D (\f1_mem[14] [1]), .SI
       (wdata[1]), .SE (n_128), .Q (\f1_mem[14] [1]));
  SDFQD0 \f1_mem_reg[14][2] (.CP (wclk), .D (\f1_mem[14] [2]), .SI
       (wdata[2]), .SE (n_128), .Q (\f1_mem[14] [2]));
  SDFQD0 \f1_mem_reg[14][4] (.CP (wclk), .D (\f1_mem[14] [4]), .SI
       (wdata[4]), .SE (n_128), .Q (\f1_mem[14] [4]));
  SDFQD0 \f1_mem_reg[14][5] (.CP (wclk), .D (\f1_mem[14] [5]), .SI
       (wdata[5]), .SE (n_128), .Q (\f1_mem[14] [5]));
  SDFQD0 \f1_mem_reg[0][0] (.CP (wclk), .D (wdata[0]), .SI
       (\f1_mem[0] [0]), .SE (n_126), .Q (\f1_mem[0] [0]));
  SDFQD0 \f1_mem_reg[14][6] (.CP (wclk), .D (\f1_mem[14] [6]), .SI
       (wdata[6]), .SE (n_128), .Q (\f1_mem[14] [6]));
  SDFQD0 \f1_mem_reg[0][2] (.CP (wclk), .D (wdata[2]), .SI
       (\f1_mem[0] [2]), .SE (n_126), .Q (\f1_mem[0] [2]));
  SDFQD0 \f1_mem_reg[8][7] (.CP (wclk), .D (\f1_mem[8] [7]), .SI
       (wdata[7]), .SE (n_125), .Q (\f1_mem[8] [7]));
  SDFQD0 \f1_mem_reg[9][0] (.CP (wclk), .D (wdata[0]), .SI
       (\f1_mem[9] [0]), .SE (n_117), .Q (\f1_mem[9] [0]));
  SDFQD0 \f1_mem_reg[9][1] (.CP (wclk), .D (wdata[1]), .SI
       (\f1_mem[9] [1]), .SE (n_117), .Q (\f1_mem[9] [1]));
  SDFQD0 \f1_mem_reg[9][3] (.CP (wclk), .D (wdata[3]), .SI
       (\f1_mem[9] [3]), .SE (n_117), .Q (\f1_mem[9] [3]));
  SDFQD0 \f1_mem_reg[9][4] (.CP (wclk), .D (wdata[4]), .SI
       (\f1_mem[9] [4]), .SE (n_117), .Q (\f1_mem[9] [4]));
  SDFQD0 \f1_mem_reg[9][5] (.CP (wclk), .D (wdata[5]), .SI
       (\f1_mem[9] [5]), .SE (n_117), .Q (\f1_mem[9] [5]));
  SDFQD0 \f1_mem_reg[3][3] (.CP (wclk), .D (wdata[3]), .SI
       (\f1_mem[3] [3]), .SE (n_130), .Q (\f1_mem[3] [3]));
  SDFQD0 \f1_mem_reg[3][0] (.CP (wclk), .D (wdata[0]), .SI
       (\f1_mem[3] [0]), .SE (n_130), .Q (\f1_mem[3] [0]));
  SDFQD0 \f1_mem_reg[3][7] (.CP (wclk), .D (wdata[7]), .SI
       (\f1_mem[3] [7]), .SE (n_130), .Q (\f1_mem[3] [7]));
  SDFQD0 \f1_mem_reg[3][4] (.CP (wclk), .D (wdata[4]), .SI
       (\f1_mem[3] [4]), .SE (n_130), .Q (\f1_mem[3] [4]));
  SDFQD0 \f1_mem_reg[3][2] (.CP (wclk), .D (wdata[2]), .SI
       (\f1_mem[3] [2]), .SE (n_130), .Q (\f1_mem[3] [2]));
  SDFQD0 \f1_mem_reg[3][6] (.CP (wclk), .D (wdata[6]), .SI
       (\f1_mem[3] [6]), .SE (n_130), .Q (\f1_mem[3] [6]));
  SDFQD0 \f1_mem_reg[8][3] (.CP (wclk), .D (\f1_mem[8] [3]), .SI
       (wdata[3]), .SE (n_125), .Q (\f1_mem[8] [3]));
  SDFQD0 \f1_mem_reg[12][3] (.CP (wclk), .D (\f1_mem[12] [3]), .SI
       (wdata[3]), .SE (n_120), .Q (\f1_mem[12] [3]));
  CKND1 g6118(.I (n_174), .ZN (n_115));
  AOI221D0 g6181__4733(.A1 (n_113), .A2 (\f1_mem[2] [6]), .B1 (n_112),
       .B2 (\f1_mem[3] [6]), .C (n_56), .ZN (n_114));
  MOAI22D1 g6145__6161(.A1 (n_133), .A2 (n_111), .B1 (n_133), .B2
       (n_111), .ZN (n_176));
  MOAI22D1 g5999__9315(.A1 (n_110), .A2 (rptr[4]), .B1 (n_110), .B2
       (rptr[4]), .ZN (n_140));
  AOI221D0 g6180__9945(.A1 (n_108), .A2 (\f1_mem[10] [0]), .B1 (n_107),
       .B2 (\f1_mem[11] [0]), .C (n_64), .ZN (n_109));
  AOI221D0 g6175__2883(.A1 (n_160), .A2 (\f1_mem[4] [3]), .B1 (n_159),
       .B2 (\f1_mem[5] [3]), .C (n_47), .ZN (n_106));
  AOI221D0 g6176__2346(.A1 (n_108), .A2 (\f1_mem[10] [5]), .B1 (n_107),
       .B2 (\f1_mem[11] [5]), .C (n_80), .ZN (n_105));
  AOI221D0 g6177__1666(.A1 (n_73), .A2 (\f1_mem[8] [4]), .B1 (n_76),
       .B2 (\f1_mem[9] [4]), .C (n_55), .ZN (n_104));
  AOI221D0 g6178__7410(.A1 (n_102), .A2 (\f1_mem[0] [1]), .B1 (n_203),
       .B2 (\f1_mem[1] [1]), .C (n_62), .ZN (n_103));
  AOI221D0 g6179__6417(.A1 (n_113), .A2 (\f1_mem[2] [2]), .B1 (n_112),
       .B2 (\f1_mem[3] [2]), .C (n_53), .ZN (n_100));
  AOI221D0 g6168__5477(.A1 (n_156), .A2 (\f1_mem[12] [7]), .B1 (n_155),
       .B2 (\f1_mem[13] [7]), .C (n_74), .ZN (n_99));
  CKND1 g6111(.I (n_138), .ZN (n_98));
  MAOI22D1 g6125__2398(.A1 (n_118), .A2 (n_97), .B1 (n_118), .B2
       (n_97), .ZN (n_174));
  MOAI22D1 g6182__5107(.A1 (n_96), .A2 (waddr[2]), .B1 (n_96), .B2
       (waddr[2]), .ZN (n_150));
  NR2XD0 g6148__6260(.A1 (n_95), .A2 (waddr[3]), .ZN (n_139));
  NR2XD0 g6149__4319(.A1 (n_95), .A2 (n_5), .ZN (n_137));
  AOI22D1 g6208__8428(.A1 (n_203), .A2 (\f1_mem[1] [4]), .B1 (n_112),
       .B2 (\f1_mem[3] [4]), .ZN (n_94));
  AOI22D1 g6193__5526(.A1 (n_102), .A2 (\f1_mem[0] [2]), .B1 (n_203),
       .B2 (\f1_mem[1] [2]), .ZN (n_93));
  AOI22D1 g6196__6783(.A1 (n_160), .A2 (\f1_mem[4] [7]), .B1 (n_203),
       .B2 (\f1_mem[1] [7]), .ZN (n_92));
  AOI22D1 g6209__3680(.A1 (n_113), .A2 (\f1_mem[2] [0]), .B1 (n_203),
       .B2 (\f1_mem[1] [0]), .ZN (n_91));
  OR2XD1 g6205__1617(.A1 (n_96), .A2 (n_41), .Z (n_131));
  AOI22D1 g6217__2802(.A1 (n_102), .A2 (\f1_mem[0] [6]), .B1 (n_203),
       .B2 (\f1_mem[1] [6]), .ZN (n_90));
  AOI22D1 g6226__1705(.A1 (n_102), .A2 (\f1_mem[0] [3]), .B1 (n_203),
       .B2 (\f1_mem[1] [3]), .ZN (n_89));
  CKND1 g6166(.I (n_133), .ZN (n_88));
  OAI211D1 g6147__5122(.A1 (n_26), .A2 (n_14), .B (n_18), .C (n_12),
       .ZN (n_119));
  MUX2ND0 g6146__8246(.I0 (raddr[3]), .I1 (n_4), .S (n_45), .ZN
       (n_138));
  NR2XD0 g6154__7098(.A1 (n_32), .A2 (n_61), .ZN (n_134));
  AOI22D1 g6195__6131(.A1 (n_85), .A2 (\f1_mem[6] [7]), .B1 (n_84), .B2
       (\f1_mem[7] [7]), .ZN (n_87));
  AOI22D1 g6184__1881(.A1 (n_85), .A2 (\f1_mem[6] [1]), .B1 (n_84), .B2
       (\f1_mem[7] [1]), .ZN (n_86));
  AOI22D1 g6185__5115(.A1 (n_108), .A2 (\f1_mem[10] [4]), .B1 (n_107),
       .B2 (\f1_mem[11] [4]), .ZN (n_83));
  AOI22D1 g6186__7482(.A1 (n_75), .A2 (\f1_mem[14] [0]), .B1 (n_65),
       .B2 (\f1_mem[15] [0]), .ZN (n_82));
  AOI22D1 g6187__4733(.A1 (n_108), .A2 (\f1_mem[10] [6]), .B1 (n_107),
       .B2 (\f1_mem[11] [6]), .ZN (n_81));
  AO22D0 g6188__6161(.A1 (n_156), .A2 (\f1_mem[12] [5]), .B1
       (\f1_mem[13] [5]), .B2 (n_155), .Z (n_80));
  AOI22D1 g6189__9315(.A1 (n_160), .A2 (\f1_mem[4] [5]), .B1 (n_159),
       .B2 (\f1_mem[5] [5]), .ZN (n_79));
  AOI22D1 g6190__9945(.A1 (n_85), .A2 (\f1_mem[6] [5]), .B1 (n_112),
       .B2 (\f1_mem[3] [5]), .ZN (n_78));
  AOI22D1 g6191__2883(.A1 (n_76), .A2 (\f1_mem[9] [2]), .B1 (n_75), .B2
       (\f1_mem[14] [2]), .ZN (n_77));
  AO22D0 g6213__2346(.A1 (n_73), .A2 (\f1_mem[8] [7]), .B1
       (\f1_mem[9] [7]), .B2 (n_76), .Z (n_74));
  AOI22D1 g6192__1666(.A1 (n_160), .A2 (\f1_mem[4] [2]), .B1 (n_159),
       .B2 (\f1_mem[5] [2]), .ZN (n_72));
  AOI22D1 g6194__7410(.A1 (n_73), .A2 (\f1_mem[8] [5]), .B1 (n_76), .B2
       (\f1_mem[9] [5]), .ZN (n_71));
  AOI22D1 g6183__6417(.A1 (n_85), .A2 (\f1_mem[6] [4]), .B1 (n_84), .B2
       (\f1_mem[7] [4]), .ZN (n_70));
  AOI22D1 g6198__5477(.A1 (n_73), .A2 (\f1_mem[8] [1]), .B1 (n_76), .B2
       (\f1_mem[9] [1]), .ZN (n_69));
  AOI22D1 g6199__2398(.A1 (n_107), .A2 (\f1_mem[11] [1]), .B1 (n_75),
       .B2 (\f1_mem[14] [1]), .ZN (n_68));
  AOI22D1 g6212__5107(.A1 (n_85), .A2 (\f1_mem[6] [0]), .B1 (n_84), .B2
       (\f1_mem[7] [0]), .ZN (n_67));
  AOI22D1 g6211__6260(.A1 (n_75), .A2 (\f1_mem[14] [7]), .B1 (n_65),
       .B2 (\f1_mem[15] [7]), .ZN (n_66));
  AO22D0 g6210__4319(.A1 (n_73), .A2 (\f1_mem[8] [0]), .B1
       (\f1_mem[9] [0]), .B2 (n_76), .Z (n_64));
  AOI22D1 g6206__8428(.A1 (n_160), .A2 (\f1_mem[4] [6]), .B1 (n_159),
       .B2 (\f1_mem[5] [6]), .ZN (n_63));
  AO22D0 g6207__5526(.A1 (n_160), .A2 (\f1_mem[4] [1]), .B1
       (\f1_mem[5] [1]), .B2 (n_159), .Z (n_62));
  DFCNQD1 \f2_wbin_reg[0] (.CDN (wrst_n), .CP (wclk), .D (n_111), .Q
       (waddr[0]));
  CKND2D1 g6202__6783(.A1 (n_60), .A2 (waddr[2]), .ZN (n_95));
  AOI21D1 g6203__3680(.A1 (n_19), .A2 (waddr[1]), .B (n_44), .ZN
       (n_133));
  INR2XD0 g6165__1617(.A1 (n_39), .B1 (n_61), .ZN (n_120));
  ND2D1 g6204__2802(.A1 (n_60), .A2 (n_43), .ZN (n_130));
  AOI22D1 g6228__1705(.A1 (n_113), .A2 (\f1_mem[2] [1]), .B1 (n_112),
       .B2 (\f1_mem[3] [1]), .ZN (n_59));
  AOI22D1 g6215__5122(.A1 (n_156), .A2 (\f1_mem[12] [0]), .B1 (n_155),
       .B2 (\f1_mem[13] [0]), .ZN (n_58));
  AOI22D1 g6216__8246(.A1 (n_156), .A2 (\f1_mem[12] [4]), .B1 (n_155),
       .B2 (\f1_mem[13] [4]), .ZN (n_57));
  AO22D0 g6218__7098(.A1 (n_85), .A2 (\f1_mem[6] [6]), .B1
       (\f1_mem[7] [6]), .B2 (n_84), .Z (n_56));
  AO22D0 g6219__6131(.A1 (n_75), .A2 (\f1_mem[14] [4]), .B1
       (\f1_mem[15] [4]), .B2 (n_65), .Z (n_55));
  AOI22D1 g6220__1881(.A1 (n_108), .A2 (\f1_mem[10] [7]), .B1 (n_107),
       .B2 (\f1_mem[11] [7]), .ZN (n_54));
  AO22D0 g6221__5115(.A1 (n_85), .A2 (\f1_mem[6] [2]), .B1
       (\f1_mem[7] [2]), .B2 (n_84), .Z (n_53));
  AOI22D1 g6222__7482(.A1 (n_108), .A2 (\f1_mem[10] [3]), .B1 (n_75),
       .B2 (\f1_mem[14] [3]), .ZN (n_52));
  AOI22D1 g6223__4733(.A1 (n_75), .A2 (\f1_mem[14] [5]), .B1 (n_65),
       .B2 (\f1_mem[15] [5]), .ZN (n_51));
  AOI22D1 g6224__6161(.A1 (n_156), .A2 (\f1_mem[12] [2]), .B1 (n_155),
       .B2 (\f1_mem[13] [2]), .ZN (n_50));
  AOI22D1 g6225__9315(.A1 (n_113), .A2 (\f1_mem[2] [3]), .B1 (n_112),
       .B2 (\f1_mem[3] [3]), .ZN (n_49));
  AOI22D1 g6227__9945(.A1 (n_73), .A2 (\f1_mem[8] [3]), .B1 (n_76), .B2
       (\f1_mem[9] [3]), .ZN (n_48));
  AO22D0 g6214__2883(.A1 (n_85), .A2 (\f1_mem[6] [3]), .B1
       (\f1_mem[7] [3]), .B2 (n_84), .Z (n_47));
  CKND1 g6157(.I (n_118), .ZN (n_46));
  CKND2D1 g6158__2346(.A1 (n_45), .A2 (raddr[3]), .ZN (n_110));
  IND2D1 g6161__1666(.A1 (n_40), .B1 (n_44), .ZN (n_129));
  IND2D1 g6153__7410(.A1 (n_42), .B1 (n_43), .ZN (n_124));
  NR2XD0 g6155__6417(.A1 (n_42), .A2 (n_41), .ZN (n_121));
  NR2XD0 g6156__5477(.A1 (n_42), .A2 (n_40), .ZN (n_122));
  IND2D1 g6162__2398(.A1 (n_41), .B1 (n_44), .ZN (n_117));
  ND2D1 g6152__5107(.A1 (n_39), .A2 (n_43), .ZN (n_126));
  NR2XD0 g6160__6260(.A1 (n_42), .A2 (n_61), .ZN (n_128));
  INR2XD0 g6164__4319(.A1 (n_39), .B1 (n_41), .ZN (n_125));
  INR2XD0 g6163__8428(.A1 (n_39), .B1 (n_40), .ZN (n_123));
  ND2D1 g6151__5526(.A1 (n_44), .A2 (n_43), .ZN (n_127));
  ND2D1 g6235__6783(.A1 (n_108), .A2 (\f1_mem[10] [1]), .ZN (n_38));
  AOI22D1 g6197__3680(.A1 (n_76), .A2 (\f1_mem[9] [6]), .B1 (n_65), .B2
       (\f1_mem[15] [6]), .ZN (n_37));
  CKND2D1 g6229__1617(.A1 (n_84), .A2 (\f1_mem[7] [5]), .ZN (n_36));
  CKND2D1 g6230__2802(.A1 (n_73), .A2 (\f1_mem[8] [2]), .ZN (n_35));
  ND2D1 g6232__1705(.A1 (n_112), .A2 (\f1_mem[3] [0]), .ZN (n_34));
  ND2D1 g6233__5122(.A1 (n_159), .A2 (\f1_mem[5] [7]), .ZN (n_33));
  INVD1 g6167(.I (n_44), .ZN (n_32));
  ND2D1 g6244__8246(.A1 (n_107), .A2 (\f1_mem[11] [3]), .ZN (n_31));
  ND2D1 g6237__7098(.A1 (n_113), .A2 (\f1_mem[2] [5]), .ZN (n_30));
  CKND2D1 g6246__6131(.A1 (n_75), .A2 (\f1_mem[14] [6]), .ZN (n_29));
  ND2D1 g6243__1881(.A1 (n_73), .A2 (\f1_mem[8] [6]), .ZN (n_28));
  ND2D1 g6236__5115(.A1 (n_113), .A2 (\f1_mem[2] [4]), .ZN (n_27));
  INVD1 g6239(.I (n_60), .ZN (n_96));
  MAOI22D1 g6159__7482(.A1 (n_26), .A2 (raddr[1]), .B1 (n_26), .B2
       (raddr[1]), .ZN (n_118));
  DFCNQD1 \e1_rbin_reg[0] (.CDN (rrst_n), .CP (rclk), .D (n_97), .Q
       (raddr[0]));
  CKND2D1 g6240__4733(.A1 (n_65), .A2 (\f1_mem[15] [1]), .ZN (n_25));
  ND2D1 g6231__6161(.A1 (n_65), .A2 (\f1_mem[15] [2]), .ZN (n_24));
  CKND2D1 g6234__9315(.A1 (n_65), .A2 (\f1_mem[15] [3]), .ZN (n_23));
  CKND2D1 g6245__9945(.A1 (n_102), .A2 (\f1_mem[0] [4]), .ZN (n_22));
  CKND2D1 g6242__2883(.A1 (n_102), .A2 (\f1_mem[0] [7]), .ZN (n_21));
  CKND2D1 g6241__2346(.A1 (n_102), .A2 (\f1_mem[0] [0]), .ZN (n_20));
  DFKCNQD1 \w1_w2r_wptr_reg[4] (.CP (rclk), .CN (w1_w2r_temp[4]), .D
       (rrst_n), .Q (w2r_wptr[4]));
  NR2XD0 g6238__1666(.A1 (n_19), .A2 (waddr[1]), .ZN (n_44));
  ND2D1 g6169__7410(.A1 (n_26), .A2 (raddr[2]), .ZN (n_18));
  DFKCNQD1 \r1_r2w_rptr_reg[4] (.CP (wclk), .CN (r1_r2w_temp[4]), .D
       (wrst_n), .Q (r2w_rptr[4]));
  NR2XD0 g6170__6417(.A1 (n_15), .A2 (n_26), .ZN (n_45));
  AO21D1 g6247__5477(.A1 (n_7), .A2 (waddr[0]), .B (n_17), .Z (n_111));
  NR2XD0 g6249__2398(.A1 (n_19), .A2 (n_1), .ZN (n_60));
  INR2XD0 g6173__5107(.A1 (n_17), .B1 (waddr[1]), .ZN (n_39));
  CKND2D1 g6172__6260(.A1 (n_17), .A2 (waddr[1]), .ZN (n_42));
  MOAI22D1 g6248__8428(.A1 (n_16), .A2 (raddr[0]), .B1 (n_16), .B2
       (raddr[0]), .ZN (n_97));
  INR2D1 g6263__5526(.A1 (n_11), .B1 (n_15), .ZN (n_75));
  NR2D1 g6259__6783(.A1 (n_14), .A2 (n_9), .ZN (n_107));
  INR2D1 g6256__3680(.A1 (n_13), .B1 (n_14), .ZN (n_113));
  INR2D1 g6264__1617(.A1 (n_13), .B1 (n_12), .ZN (n_160));
  AN2XD1 g6254__2802(.A1 (n_11), .A2 (n_10), .Z (n_73));
  NR2D1 g6265__1705(.A1 (n_12), .A2 (n_9), .ZN (n_155));
  NR2D1 g6266__5122(.A1 (n_8), .A2 (n_15), .ZN (n_84));
  NR2D1 g6267__8246(.A1 (n_14), .A2 (n_8), .ZN (n_112));
  INR2D1 g6268__7098(.A1 (n_11), .B1 (n_12), .ZN (n_156));
  INR2D1 g6269__6131(.A1 (n_11), .B1 (n_14), .ZN (n_108));
  NR2D1 g6270__1881(.A1 (n_12), .A2 (n_8), .ZN (n_159));
  NR2XD0 g6252__5115(.A1 (n_7), .A2 (waddr[0]), .ZN (n_17));
  AN2XD1 g6253__7482(.A1 (n_13), .A2 (n_10), .Z (n_102));
  INR2D1 g6255__4733(.A1 (n_10), .B1 (n_9), .ZN (n_76));
  NR2D1 g6257__6161(.A1 (n_15), .A2 (n_9), .ZN (n_65));
  IND2D1 g6260__9315(.A1 (n_7), .B1 (waddr[0]), .ZN (n_19));
  IND2D1 g6261__9945(.A1 (n_16), .B1 (raddr[0]), .ZN (n_26));
  INR2D1 g6258__2883(.A1 (n_13), .B1 (n_15), .ZN (n_85));
  DFKCNQD1 \w1_w2r_temp_reg[4] (.CP (rclk), .CN (wptr[4]), .D (rrst_n),
       .Q (w1_w2r_temp[4]));
  CKND2D1 g6279__2346(.A1 (n_5), .A2 (waddr[2]), .ZN (n_40));
  ND2D1 g6281__1666(.A1 (n_4), .A2 (raddr[0]), .ZN (n_8));
  NR2D1 g6282__7410(.A1 (n_4), .A2 (raddr[0]), .ZN (n_11));
  DFKCNQD1 \r1_r2w_temp_reg[4] (.CP (wclk), .CN (rptr[4]), .D (wrst_n),
       .Q (r1_r2w_temp[4]));
  CKND2D1 g6283__6417(.A1 (n_3), .A2 (waddr[3]), .ZN (n_41));
  ND2D1 g6285__5477(.A1 (n_0), .A2 (raddr[1]), .ZN (n_14));
  ND2D1 g6284__2398(.A1 (n_2), .A2 (raddr[2]), .ZN (n_12));
  CKND2D1 g6271__5107(.A1 (waddr[3]), .A2 (waddr[2]), .ZN (n_61));
  IND2D1 g6273__6260(.A1 (empty), .B1 (r_en), .ZN (n_16));
  NR2D1 g6274__4319(.A1 (waddr[2]), .A2 (waddr[3]), .ZN (n_43));
  NR2D1 g6276__8428(.A1 (raddr[0]), .A2 (raddr[3]), .ZN (n_13));
  IND2D1 g6272__5526(.A1 (full), .B1 (w_en), .ZN (n_7));
  NR2D1 g6280__6783(.A1 (raddr[1]), .A2 (raddr[2]), .ZN (n_10));
  ND2D1 g6275__3680(.A1 (raddr[3]), .A2 (raddr[0]), .ZN (n_9));
  ND2D1 g6277__1617(.A1 (raddr[2]), .A2 (raddr[1]), .ZN (n_15));
  XOR2D1 g2(.A1 (n_137), .A2 (wptr[4]), .Z (n_202));
  DFCND1 \f2_wbin_reg[2] (.CDN (wrst_n), .CP (wclk), .D (n_150), .Q
       (waddr[2]), .QN (n_3));
  DFCND1 \e1_rbin_reg[1] (.CDN (rrst_n), .CP (rclk), .D (n_46), .Q
       (raddr[1]), .QN (n_2));
  DFCND1 \e1_rbin_reg[3] (.CDN (rrst_n), .CP (rclk), .D (n_98), .Q
       (raddr[3]), .QN (n_4));
  DFCND1 \f2_wbin_reg[1] (.CDN (wrst_n), .CP (wclk), .D (n_88), .Q
       (waddr[1]), .QN (n_1));
  DFCND1 \e1_rbin_reg[2] (.CDN (rrst_n), .CP (rclk), .D (n_119), .Q
       (raddr[2]), .QN (n_0));
  DFCND1 \f2_wbin_reg[3] (.CDN (wrst_n), .CP (wclk), .D (n_132), .Q
       (waddr[3]), .QN (n_5));
  INR2D1 g6472(.A1 (n_10), .B1 (n_8), .ZN (n_203));
endmodule

